# Generated by cpputils-cmake.
include /home/these/Documents/quic_tunnel/quic-forwarding/build/CMakeFiles/in-tunnel.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}