# Generated by cpputils-cmake.
include /home/david/Documents/phd/quic_tunnel/quic-tunnel/build/CMakeFiles/quic-tunnel.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES}  -S ${CHK_SOURCES}